"""Markdown digest formatter."""

from datetime import datetime
from pathlib import Path


def render_markdown(digest: dict, date: str | None = None) -> str:
    """Render an intelligence digest as a beautiful Markdown document."""
    date = date or datetime.now().strftime("%Y-%m-%d")
    signal_count = digest.get("_raw_signal_count", 0)

    lines = [
        f"# 📡 Radar Intelligence Digest",
        f"",
        f"> **Date:** {date} | **Signals Analyzed:** {signal_count} | **Model:** {digest.get('_model', 'N/A')}",
        f"",
        f"---",
        f"",
        f"## 📋 Executive Summary",
        f"",
        digest.get("executive_summary", "No summary available."),
        f"",
    ]

    # Top Stories
    top_stories = digest.get("top_stories", [])
    if top_stories:
        lines.append("## 🔥 Top Stories")
        lines.append("")
        for i, story in enumerate(top_stories, 1):
            score = story.get("score", "?")
            category = story.get("category", "unknown")
            category_emoji = {
                "launch": "🚀",
                "update": "🔄",
                "trend": "📈",
                "opportunity": "💡",
                "threat": "⚠️",
                "insight": "🔍",
            }.get(category, "📌")

            lines.append(f"### {i}. {category_emoji} {story.get('title', 'Untitled')}")
            lines.append(f"")
            lines.append(f"**Score:** {score}/10 | **Category:** {category}")
            lines.append(f"")
            lines.append(f"{story.get('significance', '')}")
            lines.append(f"")

            related = story.get("signals", [])
            if related:
                lines.append(f"*Related signals:* {', '.join(related[:3])}")
                lines.append("")

    # Emerging Trends
    trends = digest.get("emerging_trends", [])
    if trends:
        lines.append("## 📈 Emerging Trends")
        lines.append("")
        for trend in trends:
            lines.append(f"### {trend.get('trend', 'Unknown trend')}")
            lines.append(f"")
            evidence = trend.get("evidence", [])
            if evidence:
                lines.append(f"**Evidence:**")
                for e in evidence:
                    lines.append(f"- {e}")
                lines.append("")
            lines.append(f"**Implication:** {trend.get('implication', '')}")
            lines.append("")

    # Action Items
    actions = digest.get("action_items", [])
    if actions:
        lines.append("## ✅ Action Items")
        lines.append("")
        for action in actions:
            priority = action.get("priority", "medium")
            emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(priority, "⚪")
            lines.append(f"- {emoji} **[{priority.upper()}]** {action.get('action', '')}")
            if action.get("reason"):
                lines.append(f"  - *Why:* {action['reason']}")
        lines.append("")

    # Source Breakdown
    sources = digest.get("signals_by_source", {})
    if sources:
        lines.append("## 📊 Sources Breakdown")
        lines.append("")
        lines.append("| Source | Signals | Highlights |")
        lines.append("|--------|---------|------------|")
        for source, data in sources.items():
            count = data.get("count", 0)
            highlights = ", ".join(data.get("highlights", [])[:3])
            emoji = {
                "github": "🐙",
                "hackernews": "📰",
                "producthunt": "🚀",
                "rss": "📡",
                "web": "🌐",
            }.get(source, "📌")
            lines.append(f"| {emoji} {source} | {count} | {highlights or '-'} |")
        lines.append("")

    # Noise filtered
    noise = digest.get("noise_filtered", "")
    if noise and noise != "N/A":
        lines.append(f"## 🗑️ Filtered Noise")
        lines.append(f"")
        lines.append(noise)
        lines.append("")

    lines.extend([
        "---",
        "",
        f"*Generated by [Radar Agent](https://github.com/Jaxz714/radar-agent) at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
    ])

    return "\n".join(lines)


def save_markdown(digest: dict, output_dir: Path, date: str | None = None) -> Path:
    """Save a markdown digest to file."""
    date = date or datetime.now().strftime("%Y-%m-%d")
    output_dir.mkdir(parents=True, exist_ok=True)
    filepath = output_dir / f"radar-{date}.md"
    content = render_markdown(digest, date)
    filepath.write_text(content, encoding="utf-8")
    return filepath
